# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpegTsAnalyzer < Formula
  desc "An analyzer for MPEG-2 Transport Stream (ISO/IEC 13818-1)"
  homepage "https://github.com/small-teton/mpeg-ts-analyzer"
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.5.0/mpeg-ts-analyzer_Darwin_x86_64.tar.gz"
      sha256 "fb177fd6a63a1bd542ef6e38aebc3479b465a8a8bed927fb04a271badd725c7b"

      def install
        bin.install "mpeg-ts-analyzer"
      end
    end
    on_arm do
      url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.5.0/mpeg-ts-analyzer_Darwin_arm64.tar.gz"
      sha256 "43517f808551f4416d76eff82eba7c1a1041dcede4bda741246b1cf63dd551a1"

      def install
        bin.install "mpeg-ts-analyzer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.5.0/mpeg-ts-analyzer_Linux_x86_64.tar.gz"
        sha256 "b194c73b2757af32f460a5bf42c63456c4605ec47aefbec268fe562b32746d9a"

        def install
          bin.install "mpeg-ts-analyzer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.5.0/mpeg-ts-analyzer_Linux_arm64.tar.gz"
        sha256 "4056d242ad23d3d50016f55672ac954d94ce8a450523c29bb0b35b913d3bb20b"

        def install
          bin.install "mpeg-ts-analyzer"
        end
      end
    end
  end
end
