# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpegTsAnalyzer < Formula
  desc "An analyzer for MPEG-2 Transport Stream (ISO/IEC 13818-1)"
  homepage "https://github.com/small-teton/mpeg-ts-analyzer"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.3.0/mpeg-ts-analyzer_Darwin_x86_64.tar.gz"
      sha256 "342e58cc95170b1996ef0c98e3ac0b28fa53799c4d81646c0a4b1a2db7af9be7"

      def install
        bin.install "mpeg-ts-analyzer"
      end
    end
    on_arm do
      url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.3.0/mpeg-ts-analyzer_Darwin_arm64.tar.gz"
      sha256 "987b6b2acc546e42a58d631581d04a718bbb2a4435c4bd5f6808550a3ec00a4c"

      def install
        bin.install "mpeg-ts-analyzer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.3.0/mpeg-ts-analyzer_Linux_x86_64.tar.gz"
        sha256 "37196d450223c618f2d8f856de29c4921130f1a1da51f28679f0170245a66a07"

        def install
          bin.install "mpeg-ts-analyzer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/small-teton/mpeg-ts-analyzer/releases/download/v1.3.0/mpeg-ts-analyzer_Linux_arm64.tar.gz"
        sha256 "cdc61c6ae0d4da6abefcb512c0e146fab8118a92d828fc1dc5909183de307c09"

        def install
          bin.install "mpeg-ts-analyzer"
        end
      end
    end
  end
end
